{{- if or .Values.api.ingress.enabled .Values.web.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "winmem.fullname" . }}-ingress
  labels:
    {{- include "winmem.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.ingress.annotations }}
    {{- toYaml .Values.api.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.web.ingress.enabled }}
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "winmem.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.api.ingress.enabled }}
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "winmem.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end -}}
