apiVersion: v1
kind: Secret
metadata:
  name: {{ include "winmem.fullname" . }}-secrets
  labels:
    {{- include "winmem.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.external.databaseUrl | quote }}
  REDIS_URL: {{ .Values.external.redisUrl | quote }}
  WINMEM_API_KEY_ADMIN: {{ .Values.secrets.apiKeyAdmin | quote }}
  WINMEM_API_KEY_READONLY: {{ .Values.secrets.apiKeyReadonly | quote }}
